const fs = require('fs');
const VOCAB_PATH = 'c:/Users/johnh/OneDrive/Documents/indak/data/vocabulary.json';
const PROG_PATH = 'c:/Users/johnh/OneDrive/Documents/indak/data/audit_progress.json';

const data = JSON.parse(fs.readFileSync(VOCAB_PATH, 'utf8'));

// Corrections for 50-300 based on Native Hiligaynon standards
const batch_50_300 = [
    { word: "Hubóg", syllables: ["Hu", "bóg"], stress_index: 1, meaning: "Drunk", category: "Adjectives" },
    { word: "Bugnáw", syllables: ["Bug", "náw"], stress_index: 1, meaning: "Cold", category: "Adjectives" },
    { word: "Punò", syllables: ["Pu", "nò"], stress_index: 1, meaning: "Tree / Trunk / Source", category: "Nouns" },
    { word: "Káhoy", syllables: ["Ká", "hoy"], stress_index: 0, meaning: "Wood / Log", category: "Nouns" },
    { word: "Búlak", syllables: ["Bú", "lak"], stress_index: 0, meaning: "Flower", category: "Nouns" },
    { word: "Tunà", syllables: ["Tu", "nà"], stress_index: 1, meaning: "Land / Earth / Soil", category: "Nouns" },
    { word: "Sugâ", syllables: ["Su", "gâ"], stress_index: 1, meaning: "Light / Lamps", category: "Nouns" },
    { word: "Pangánod", syllables: ["Pa", "ngá", "nod"], stress_index: 1, meaning: "Cloud", category: "Nouns" },
    { word: "Hángin", syllables: ["Há", "ngin"], stress_index: 0, meaning: "Wind / Air", category: "Nouns" },
    { word: "Kilát", syllables: ["Ki", "lát"], stress_index: 1, meaning: "Lightning", category: "Nouns" },
    { word: "Kunô", syllables: ["Ku", "nô"], stress_index: 1, meaning: "They say / Rumor has it", category: "Grammar & Particles" },
    { word: "Tí", syllables: ["Tí"], stress_index: 0, meaning: "Well / So / Then", category: "Grammar & Particles" },
    { word: "Na", syllables: ["Na"], stress_index: 0, meaning: "Already / Now", category: "Grammar & Particles" },
    { word: "Kapé", syllables: ["Ka", "pé"], stress_index: 1, meaning: "Coffee", category: "Nouns" },
    { word: "Tinápay", syllables: ["Ti", "ná", "pay"], stress_index: 1, meaning: "Bread", category: "Nouns" },
    { word: "Súd-an", syllables: ["Súd", "an"], stress_index: 0, meaning: "Viand / Main Dish", category: "Nouns" },
    { word: "Isdà", syllables: ["Is", "dà"], stress_index: 1, meaning: "Fish", category: "Nouns" },
    { word: "Karné", syllables: ["Kar", "né"], stress_index: 1, meaning: "Meat", category: "Nouns" },
    { word: "Prútas", syllables: ["Prú", "tas"], stress_index: 0, meaning: "Fruit", category: "Nouns" },
    { word: "Túlog", syllables: ["Tú", "log"], stress_index: 0, meaning: "Sleep", category: "Verbs" },
    { word: "Búgtaw", syllables: ["Bú", "gtaw"], stress_index: 0, meaning: "Awake / Wake up", category: "Verbs" },
    { word: "Língkod", syllables: ["Líng", "kod"], stress_index: 0, meaning: "Sit down", category: "Verbs" },
    { word: "Tíndog", syllables: ["Tín", "dog"], stress_index: 0, meaning: "Stand up", category: "Verbs" },
    { word: "Památì", syllables: ["Pa", "má", "tì"], stress_index: 1, meaning: "Listen", category: "Verbs" },
    { word: "Istória", syllables: ["Is", "tó", "ria"], stress_index: 1, meaning: "Talk / Story / Conversation", category: "Nouns" },
    { word: "Bakál", syllables: ["Ba", "kál"], stress_index: 1, meaning: "Buy", category: "Verbs" },
    { word: "Bulíg", syllables: ["Bu", "líg"], stress_index: 1, meaning: "Help / Assist", category: "Verbs" },
    { word: "Hátag", syllables: ["Há", "tag"], stress_index: 0, meaning: "Give", category: "Verbs" },
    { word: "Lántaw", syllables: ["Lán", "taw"], stress_index: 0, meaning: "Watch / Look", category: "Verbs" },
    { word: "Pulós", syllables: ["Pu", "lós"], stress_index: 1, meaning: "Usefulness / Value", category: "Nouns" },
    { word: "Kamúsa", syllables: ["Ka", "mú", "sa"], stress_index: 1, meaning: "How are you", category: "Greetings & Phrases" },
    { word: "Paanó", syllables: ["Pa", "a", "nó"], stress_index: 2, meaning: "How", category: "Grammar & Particles" },
    { word: "Anó", syllables: ["A", "nó"], stress_index: 1, meaning: "What", category: "Grammar & Particles" },
    { word: "Diín", syllables: ["Di", "ín"], stress_index: 1, meaning: "Where", category: "Grammar & Particles" },
    { word: "Sín-o", syllables: ["Sín", "o"], stress_index: 0, meaning: "Who", category: "Grammar & Particles" },
    { word: "Ímo", syllables: ["Í", "mo"], stress_index: 0, meaning: "Yours / Your", category: "Pronouns" },
    { word: "Ákon", syllables: ["Á", "kon"], stress_index: 0, meaning: "Mine / My", category: "Pronouns" },
    { word: "Íya", syllables: ["Í", "ya"], stress_index: 0, meaning: "His / Her", category: "Pronouns" },
    { word: "Ínyo", syllables: ["Í", "nyo"], stress_index: 0, meaning: "Yours (plural) / Your", category: "Pronouns" },
    { word: "Ámon", syllables: ["Á", "mon"], stress_index: 0, meaning: "Ours (exclusive) / Our", category: "Pronouns" },
    { word: "Áton", syllables: ["Á", "ton"], stress_index: 0, meaning: "Ours (inclusive) / Our", category: "Pronouns" },
    { word: "Íla", syllables: ["Í", "la"], stress_index: 0, meaning: "Theirs / Their", category: "Pronouns" },
    { word: "Palanggâ", syllables: ["Pa", "lan", "ggâ"], stress_index: 2, meaning: "Love / Beloved", category: "Verbs" },
    { word: "Hídlaw", syllables: ["Híd", "law"], stress_index: 0, meaning: "Miss / Yearn for", category: "Verbs" },
    { word: "Intsíndi", syllables: ["In", "tsín", "di"], stress_index: 1, meaning: "Understand", category: "Verbs" },
    { word: "Hámbal", syllables: ["Hám", "bal"], stress_index: 0, meaning: "Speak / Talk", category: "Verbs" },
    { word: "Bwás", syllables: ["Bwás"], stress_index: 0, meaning: "Tomorrow", category: "Grammar & Particles" },
    { word: "Kahápon", syllables: ["Ka", "há", "pon"], stress_index: 1, meaning: "Yesterday", category: "Grammar & Particles" },
    { word: "Dápat", syllables: ["Dá", "pat"], stress_index: 0, meaning: "Must / Should", category: "Grammar & Particles" },
    { word: "Kópya", syllables: ["Kó", "pya"], stress_index: 0, meaning: "Copy", category: "Nouns" },
    { word: "Autóridád", syllables: ["Au", "tó", "ri", "dád"], stress_index: 3, meaning: "Authority", category: "Nouns" },
    { word: "Kán-on", syllables: ["Kán", "on"], stress_index: 0, meaning: "Cooked Rice / To eat", category: "Nouns" },
    { word: "Ábi", syllables: ["Á", "bi"], stress_index: 0, meaning: "Thought / Suppose", category: "Grammar & Particles" },
    { word: "Kamatúoran", syllables: ["Ka", "ma", "tú", "o", "ran"], stress_index: 2, meaning: "Truth", category: "Nouns" },
    { word: "Mensáhe", syllables: ["Men", "sá", "he"], stress_index: 1, meaning: "Message", category: "Nouns" },
    { word: "Paági", syllables: ["Pa", "á", "gi"], stress_index: 1, meaning: "Through / By means of", category: "Grammar & Particles" },
    { word: "Prayer", syllables: ["Pray", "er"], stress_index: 0, meaning: "Prayer", category: "Nouns" },
    { word: "Bása", syllables: ["Bá", "sa"], stress_index: 0, meaning: "Read", category: "Verbs" },
    { word: "Tuón", syllables: ["Tu", "ón"], stress_index: 1, meaning: "Study", category: "Verbs" },
    { word: "Diyós", syllables: ["Di", "yós"], stress_index: 1, meaning: "God", category: "Nouns" },
    { word: "Bátì", syllables: ["Bá", "tì"], stress_index: 0, meaning: "Hear / Feel", category: "Verbs" },
    { word: "Uswág", syllables: ["Us", "wág"], stress_index: 1, meaning: "Progress / Prosper", category: "Verbs" },
    { word: "Hápit", syllables: ["Há", "pit"], stress_index: 0, meaning: "Visit / Drop by", category: "Verbs" },
    { word: "Yúhum", syllables: ["Yú", "hum"], stress_index: 0, meaning: "Smile", category: "Nouns" },
    { word: "Ábtik", syllables: ["Áb", "tik"], stress_index: 0, meaning: "Active / Fast", category: "Adjectives" },
    { word: "Gúbot", syllables: ["Gú", "bot"], stress_index: 0, meaning: "Chaos / Mess", category: "Nouns" },
    { word: "Taláng", syllables: ["Ta", "láng"], stress_index: 1, meaning: "Lost / Stray", category: "Adjectives" },
    { word: "Ámlig", syllables: ["Ám", "lig"], stress_index: 0, meaning: "Care / Protect", category: "Verbs" },
    { word: "Saád", syllables: ["Sa", "ád"], stress_index: 1, meaning: "Promise", category: "Nouns" },
    { word: "Wákal", syllables: ["Wá", "kal"], stress_index: 0, meaning: "Talkative / Prattle", category: "Adjectives" },
    { word: "Abáw", syllables: ["A", "báw"], stress_index: 1, meaning: "Wow / Oh my", category: "Greetings & Phrases" },
    { word: "Aragóy", syllables: ["A", "ra", "góy"], stress_index: 2, meaning: "Ouch", category: "Greetings & Phrases" },
    { word: "Sigúro", syllables: ["Si", "gú", "ro"], stress_index: 1, meaning: "Maybe / Perhaps", category: "Grammar & Particles" },
    { word: "Arí", syllables: ["A", "rí"], stress_index: 1, meaning: "Here (it is)", category: "Grammar & Particles" },
    { word: "Ábut", syllables: ["Á", "but"], stress_index: 0, meaning: "Arrive / Reach", category: "Verbs" },
    { word: "Álay-áy", syllables: ["Á", "lay", "áy"], stress_index: 2, meaning: "Support / Fragile", category: "Adjectives" },
    { word: "Ábonár", syllables: ["Á", "bo", "nár"], stress_index: 2, meaning: "Pay extra / Reimburse", category: "Verbs" },
    { word: "Ábat", syllables: ["Á", "bat"], stress_index: 0, meaning: "Sense / Feel", category: "Verbs" },
    { word: "Tigaylô", syllables: ["Ti", "gay", "lô"], stress_index: 2, meaning: "Exchange / Trade", category: "Verbs" },
    { word: "Sáylo", syllables: ["Sáy", "lo"], stress_index: 0, meaning: "Pass / Go beyond", category: "Verbs" },
    { word: "Angán-angán", syllables: ["A", "ngán", "a", "ngán"], stress_index: 3, meaning: "Hesitate / Delay", category: "Verbs" },
    { word: "Bátì", syllables: ["Bá", "tì"], stress_index: 0, meaning: "Hear", category: "Verbs" },
    { word: "Húlum", syllables: ["Hú", "lum"], stress_index: 0, meaning: "Soak", category: "Verbs" },
    { word: "Hákot", syllables: ["Há", "kot"], stress_index: 0, meaning: "Transport / Haul", category: "Verbs" },
    { word: "Bug-át", syllables: ["Bug", "át"], stress_index: 1, meaning: "Heavy", category: "Adjectives" },
    { word: "Mág-an", syllables: ["Mág", "an"], stress_index: 0, meaning: "Light (weight)", category: "Adjectives" },
    { word: "Gín-ot", syllables: ["Gín", "ot"], stress_index: 0, meaning: "Stuffy / Humid", category: "Adjectives" },
    { word: "Láyngat", syllables: ["Láy", "ngat"], stress_index: 0, meaning: "Stagger / Lean", category: "Verbs" },
    { word: "Kúhad", syllables: ["Kú", "had"], stress_index: 0, meaning: "Extract / Scoop", category: "Verbs" },
    { word: "Líp-ot", syllables: ["Líp", "ot"], stress_index: 0, meaning: "Short cut / Brief", category: "Adjectives" },
    { word: "Dágdag", syllables: ["Dág", "dag"], stress_index: 0, meaning: "Drop / Fall", category: "Verbs" },
    { word: "Púlot", syllables: ["Pú", "lot"], stress_index: 0, meaning: "Pick up", category: "Verbs" },
    { word: "Lúnod", syllables: ["Lú", "nod"], stress_index: 0, meaning: "Sink / Drown", category: "Verbs" },
    { word: "Táas", syllables: ["Tá", "as"], stress_index: 0, meaning: "High / Tall", category: "Adjectives" },
    { word: "Nubò", syllables: ["Nu", "bò"], stress_index: 1, meaning: "Low / Short", category: "Adjectives" },
    { word: "Dakô", syllables: ["Da", "kô"], stress_index: 1, meaning: "Big", category: "Adjectives" },
    { word: "Gamáy", syllables: ["Ga", "máy"], stress_index: 1, meaning: "Small", category: "Adjectives" },
    { word: "Matám-is", syllables: ["Ma", "tám", "is"], stress_index: 1, meaning: "Sweet", category: "Adjectives" },
    { word: "Maaslúm", syllables: ["Ma", "as", "lúm"], stress_index: 2, meaning: "Sour", category: "Adjectives" },
    { word: "Mapait", syllables: ["Ma", "pa", "it"], stress_index: 2, meaning: "Bitter", category: "Adjectives" },
    { word: "Maalat", syllables: ["Ma", "a", "lat"], stress_index: 2, meaning: "Salty", category: "Adjectives" },
    { word: "Mahánghang", syllables: ["Ma", "háng", "hang"], stress_index: 1, meaning: "Spicy", category: "Adjectives" },
    { word: "Gatóm", syllables: ["Ga", "tóm"], stress_index: 1, meaning: "Hungry", category: "Adjectives" },
    { word: "Busóg", syllables: ["Bu", "sóg"], stress_index: 1, meaning: "Full (stomach)", category: "Adjectives" },
    { word: "Uháw", syllables: ["U", "háw"], stress_index: 1, meaning: "Thirsty", category: "Adjectives" },
    { word: "Káon", syllables: ["Ká", "on"], stress_index: 0, meaning: "Eat", category: "Verbs" },
    { word: "Inúm", syllables: ["I", "núm"], stress_index: 1, meaning: "Drink", category: "Verbs" },
    { word: "Lutò", syllables: ["Lu", "tò"], stress_index: 1, meaning: "Cook", category: "Verbs" },
    { word: "Húgas", syllables: ["Hú", "gas"], stress_index: 0, meaning: "Wash (dishes/hands)", category: "Verbs" },
    { word: "Lábhan", syllables: ["Láb", "han"], stress_index: 0, meaning: "Wash (clothes)", category: "Verbs" },
    { word: "Trabáho", syllables: ["Tra", "bá", "ho"], stress_index: 1, meaning: "Work", category: "Verbs" },
    { word: "Lakát", syllables: ["La", "kát"], stress_index: 1, meaning: "Walk / Go", category: "Verbs" },
    { word: "Dalágan", syllables: ["Da", "lá", "gan"], stress_index: 1, meaning: "Run", category: "Verbs" },
    { word: "Tsalé", syllables: ["Tsa", "lé"], stress_index: 1, meaning: "Dance", category: "Verbs" },
    { word: "Kantá", syllables: ["Kan", "tá"], stress_index: 1, meaning: "Sing", category: "Verbs" },
    { word: "Simba", syllables: ["Sim", "ba"], stress_index: 0, meaning: "Worship / Mass", category: "Verbs" },
    { word: "Menská", syllables: ["Men", "ská"], stress_index: 1, meaning: "Pray / Chant", category: "Verbs" },
    { word: "Pray", syllables: ["Pray"], stress_index: 0, meaning: "Pray", category: "Verbs" },
    { word: "Amurá", syllables: ["A", "mu", "rá"], stress_index: 2, meaning: "Wake up Early", category: "Verbs" },
    { word: "Dúgay", syllables: ["Dú", "gay"], stress_index: 0, meaning: "Long time", category: "Adjectives" },
    { word: "Mabigát", syllables: ["Ma", "bi", "gát"], stress_index: 2, meaning: "Heavy (physical/emotional)", category: "Adjectives" },
    { word: "Salá", syllables: ["Sa", "lá"], stress_index: 1, meaning: "Sin / Error", category: "Nouns" },
    { word: "Gugmá", syllables: ["Gug", "má"], stress_index: 1, meaning: "Love (romantic)", category: "Nouns" },
    { word: "Kalípay", syllables: ["Ka", "lí", "pay"], stress_index: 1, meaning: "Happiness", category: "Nouns" },
    { word: "Kasubô", syllables: ["Ka", "su", "bô"], stress_index: 2, meaning: "Sadness", category: "Nouns" },
    { word: "Kahangít", syllables: ["Ka", "ha", "ngít"], stress_index: 2, meaning: "Anger", category: "Nouns" },
    { word: "Kahádlok", syllables: ["Ka", "há", "dlok"], stress_index: 1, meaning: "Fear", category: "Nouns" },
    { word: "Mata", syllables: ["Ma", "ta"], stress_index: 0, meaning: "Eye", category: "Nouns" },
    { word: "Tulyá", syllables: ["Tu", "lyá"], stress_index: 1, meaning: "Ears", category: "Nouns" },
    { word: "Irúng", syllables: ["I", "rúng"], stress_index: 1, meaning: "Nose", category: "Nouns" },
    { word: "Bà-bâ", syllables: ["Bà", "bâ"], stress_index: 0, meaning: "Mouth", category: "Nouns" },
    { word: "Rikit", syllables: ["Ri", "kit"], stress_index: 0, meaning: "Teeth", category: "Nouns" },
    { word: "Dilâ", syllables: ["Di", "lâ"], stress_index: 1, meaning: "Tongue", category: "Nouns" },
    { word: "Ulo", syllables: ["U", "lo"], stress_index: 0, meaning: "Head", category: "Nouns" },
    { word: "Ramúh", syllables: ["Ra", "múh"], stress_index: 1, meaning: "Hair", category: "Nouns" },
    { word: "Náu", syllables: ["Náu"], stress_index: 0, meaning: "Neck", category: "Nouns" },
    { word: "Abága", syllables: ["A", "bá", "ga"], stress_index: 1, meaning: "Shoulder", category: "Nouns" },
    { word: "Kamot", syllables: ["Ka", "mot"], stress_index: 0, meaning: "Hand", category: "Nouns" },
    { word: "Tákô", syllables: ["Tá", "kô"], stress_index: 0, meaning: "Feet", category: "Nouns" },
    { word: "Lutô", syllables: ["Lu", "tò"], stress_index: 1, meaning: "Lungs", category: "Nouns" },
    { word: "Kasingkásing", syllables: ["Ka", "sing", "ká", "sing"], stress_index: 2, meaning: "Heart", category: "Nouns" },
    { word: "Atáy", syllables: ["A", "táy"], stress_index: 1, meaning: "Liver", category: "Nouns" },
    { word: "Tiná-e", syllables: ["Ti", "ná", "e"], stress_index: 1, meaning: "Intestines", category: "Nouns" },
    { word: "Tul-án", syllables: ["Tul", "án"], stress_index: 1, meaning: "Bone", category: "Nouns" },
    { word: "Dugô", syllables: ["Du", "gô"], stress_index: 1, meaning: "Blood", category: "Nouns" },
    { word: "Pánit", syllables: ["Pá", "nit"], stress_index: 0, meaning: "Skin", category: "Nouns" },
    { word: "Laláki", syllables: ["La", "lá", "ki"], stress_index: 1, meaning: "Man / Male", category: "Nouns" },
    { word: "Babáye", syllables: ["Ba", "bá", "ye"], stress_index: 1, meaning: "Woman / Female", category: "Nouns" },
    { word: "Bátà", syllables: ["Bá", "tà"], stress_index: 0, meaning: "Child", category: "Nouns" },
    { word: "Tatay", syllables: ["Ta", "tay"], stress_index: 0, meaning: "Father", category: "Nouns" },
    { word: "Nanay", syllables: ["Na", "nay"], stress_index: 0, meaning: "Mother", category: "Nouns" },
    { word: "Atáy", syllables: ["A", "táy"], stress_index: 1, meaning: "Child / Son / Daughter", category: "Nouns" },
    { word: "Lólo", syllables: ["Ló", "lo"], stress_index: 0, meaning: "Grandfather", category: "Nouns" },
    { word: "Lóla", syllables: ["Ló", "la"], stress_index: 0, meaning: "Grandmother", category: "Nouns" },
    { word: "Ápo", syllables: ["Á", "po"], stress_index: 0, meaning: "Grandchild", category: "Nouns" },
    { word: "Tío", syllables: ["Tí", "o"], stress_index: 0, meaning: "Uncle", category: "Nouns" },
    { word: "Tía", syllables: ["Tí", "a"], stress_index: 0, meaning: "Aunt", category: "Nouns" },
    { word: "Prímo", syllables: ["Prí", "mo"], stress_index: 0, meaning: "Cousin (male)", category: "Nouns" },
    { word: "Príma", syllables: ["Prí", "ma"], stress_index: 0, meaning: "Cousin (female)", category: "Nouns" },
    { word: "Amígo", syllables: ["A", "mí", "go"], stress_index: 1, meaning: "Friend (male)", category: "Nouns" },
    { word: "Amíga", syllables: ["A", "mí", "ga"], stress_index: 1, meaning: "Friend (female)", category: "Nouns" },
    { word: "Kasípiling", syllables: ["Ka", "sí", "pi", "ling"], stress_index: 1, meaning: "Neighbor", category: "Nouns" },
    { word: "Mistro", syllables: ["Mis", "tro"], stress_index: 0, meaning: "Teacher (male)", category: "Nouns" },
    { word: "Mistra", syllables: ["Mis", "tra"], stress_index: 0, meaning: "Teacher (female)", category: "Nouns" },
    { word: "Istúdyante", syllables: ["Is", "tú", "dyan", "te"], stress_index: 1, meaning: "Student", category: "Nouns" },
    { word: "Dókutor", syllables: ["Dó", "ku", "tor"], stress_index: 0, meaning: "Doctor", category: "Nouns" },
    { word: "Nars", syllables: ["Nars"], stress_index: 0, meaning: "Nurse", category: "Nouns" },
    { word: "Polís", syllables: ["Po", "lís"], stress_index: 1, meaning: "Police", category: "Nouns" },
    { word: "Súndalo", syllables: ["Sún", "da", "lo"], stress_index: 0, meaning: "Soldier", category: "Nouns" },
    { word: "Abogádo", syllables: ["A", "bo", "gá", "do"], stress_index: 2, meaning: "Lawyer", category: "Nouns" },
    { word: "Arkitékto", syllables: ["Ar", "ki", "ték", "to"], stress_index: 2, meaning: "Architect", category: "Nouns" },
    { word: "Inginyéro", syllables: ["In", "gi", "nyé", "ro"], stress_index: 2, meaning: "Engineer", category: "Nouns" },
    { word: "Pílot", syllables: ["Pí", "lot"], stress_index: 0, meaning: "Pilot", category: "Nouns" },
    { word: "Kaptán", syllables: ["Kap", "tán"], stress_index: 1, meaning: "Captain", category: "Nouns" },
    { word: "Áktor", syllables: ["Ák", "tor"], stress_index: 0, meaning: "Actor", category: "Nouns" },
    { word: "Áktris", syllables: ["Ák", "tris"], stress_index: 0, meaning: "Actress", category: "Nouns" },
    { word: "Músíko", syllables: ["Mú", "sí", "ko"], stress_index: 0, meaning: "Musician", category: "Nouns" },
    { word: "Pórtero", syllables: ["Pór", "te", "ro"], stress_index: 0, meaning: "Porter", category: "Nouns" },
    { word: "Karpintéro", syllables: ["Kar", "pin", "té", "ro"], stress_index: 2, meaning: "Carpenter", category: "Nouns" },
    { word: "Pintór", syllables: ["Pin", "tór"], stress_index: 1, meaning: "Painter", category: "Nouns" },
    { word: "Drayber", syllables: ["Dray", "ber"], stress_index: 0, meaning: "Driver", category: "Nouns" },
    { word: "Kondukto", syllables: ["Kon", "duk", "to"], stress_index: 1, meaning: "Conductor", category: "Nouns" },
    { word: "Tindéro", syllables: ["Tin", "dé", "ro"], stress_index: 1, meaning: "Seller (male)", category: "Nouns" },
    { word: "Tindéra", syllables: ["Tin", "dé", "ra"], stress_index: 1, meaning: "Seller (female)", category: "Nouns" },
    { word: "Kostúmer", syllables: ["Kos", "tú", "mer"], stress_index: 1, meaning: "Customer", category: "Nouns" },
    { word: "Presyo", syllables: ["Pres", "yo"], stress_index: 0, meaning: "Price", category: "Nouns" },
    { word: "Baryút", syllables: ["Bar", "yút"], stress_index: 1, meaning: "Change / Coins", category: "Nouns" },
    { word: "Kwárta", syllables: ["Kwár", "ta"], stress_index: 0, meaning: "Money", category: "Nouns" },
    { word: "Bángko", syllables: ["Báng", "ko"], stress_index: 0, meaning: "Bank", category: "Nouns" },
    { word: "Pasapórte", syllables: ["Pa", "sa", "pór", "te"], stress_index: 2, meaning: "Passport", category: "Nouns" },
    { word: "Tiket", syllables: ["Ti", "ket"], stress_index: 0, meaning: "Ticket", category: "Nouns" },
    { word: "Maléta", syllables: ["Ma", "lé", "ta"], stress_index: 1, meaning: "Suitcase", category: "Nouns" },
    { word: "Bag", syllables: ["Bag"], stress_index: 0, meaning: "Bag", category: "Nouns" },
    { word: "Eropláno", syllables: ["E", "ro", "plá", "no"], stress_index: 2, meaning: "Airplane", category: "Nouns" },
    { word: "Bárko", syllables: ["Bár", "ko"], stress_index: 0, meaning: "Ship / Boat", category: "Nouns" },
    { word: "Bus", syllables: ["Bus"], stress_index: 0, meaning: "Bus", category: "Nouns" },
    { word: "Takú", syllables: ["Ta", "kú"], stress_index: 1, meaning: "Train", category: "Nouns" },
    { word: "Kótse", syllables: ["Kót", "se"], stress_index: 0, meaning: "Car", category: "Nouns" },
    { word: "Motor", syllables: ["Mo", "tor"], stress_index: 1, meaning: "Motorcycle / Engine", category: "Nouns" },
    { word: "Bisikléta", syllables: ["Bi", "si", "klé", "ta"], stress_index: 2, meaning: "Bicycle", category: "Nouns" },
    { word: "Laníg", syllables: ["La", "níg"], stress_index: 1, meaning: "Path / Road", category: "Nouns" },
    { word: "Kálsa", syllables: ["Kál", "sa"], stress_index: 0, meaning: "Street / Road", category: "Nouns" },
    { word: "Baláy", syllables: ["Ba", "láy"], stress_index: 1, meaning: "House", category: "Nouns" },
    { word: "Kwartu", syllables: ["Kwar", "tu"], stress_index: 1, meaning: "Room", category: "Nouns" },
    { word: "Hígado", syllables: ["Hí", "ga", "do"], stress_index: 0, meaning: "Bed", category: "Nouns" },
    { word: "Latú", syllables: ["La", "tú"], stress_index: 1, meaning: "Chair", category: "Nouns" },
    { word: "Lamésa", syllables: ["La", "mé", "sa"], stress_index: 1, meaning: "Table", category: "Nouns" },
    { word: "Suga", syllables: ["Su", "ga"], stress_index: 0, meaning: "Light", category: "Nouns" },
    { word: "Tv", syllables: ["Tv"], stress_index: 0, meaning: "Television", category: "Nouns" },
    { word: "Radyo", syllables: ["Rad", "yo"], stress_index: 0, meaning: "Radio", category: "Nouns" },
    { word: "Kompyúter", syllables: ["Kom", "pyú", "ter"], stress_index: 1, meaning: "Computer", category: "Nouns" },
    { word: "Selpon", syllables: ["Sel", "pon"], stress_index: 0, meaning: "Cell phone", category: "Nouns" },
    { word: "Libro", syllables: ["Lib", "ro"], stress_index: 0, meaning: "Book", category: "Nouns" },
    { word: "Papél", syllables: ["Pa", "pél"], stress_index: 1, meaning: "Paper", category: "Nouns" },
    { word: "Bolpen", syllables: ["Bol", "pen"], stress_index: 0, meaning: "Pen", category: "Nouns" },
    { word: "Lapis", syllables: ["La", "pis"], stress_index: 0, meaning: "Pencil", category: "Nouns" },
    { word: "Bag", syllables: ["Bag"], stress_index: 0, meaning: "Backpack / Bag", category: "Nouns" },
    { word: "Súlat", syllables: ["Sú", "lat"], stress_index: 0, meaning: "Letter / Writing", category: "Nouns" },
    { word: "Skul", syllables: ["Skul"], stress_index: 0, meaning: "School", category: "Nouns" },
    { word: "Unibérsitád", syllables: ["U", "ni", "bér", "si", "tád"], stress_index: 4, meaning: "University", category: "Nouns" },
    { word: "Simba", syllables: ["Sim", "ba"], stress_index: 0, meaning: "Church", category: "Nouns" },
    { word: "Ospitál", syllables: ["Os", "pi", "tál"], stress_index: 2, meaning: "Hospital", category: "Nouns" },
    { word: "Tindáhan", syllables: ["Tin", "dá", "han"], stress_index: 1, meaning: "Shop / Store", category: "Nouns" },
    { word: "Márket", syllables: ["Már", "ket"], stress_index: 0, meaning: "Market", category: "Nouns" },
    { word: "Résto", syllables: ["Rés", "to"], stress_index: 0, meaning: "Restaurant", category: "Nouns" },
    { word: "Hótel", syllables: ["Hó", "tel"], stress_index: 0, meaning: "Hotel", category: "Nouns" },
    { word: "Bangko", syllables: ["Bang", "ko"], stress_index: 0, meaning: "Bench / Bank", category: "Nouns" },
    { word: "Áiroport", syllables: ["Ái", "ro", "port"], stress_index: 0, meaning: "Airport", category: "Nouns" },
    { word: "Istasyon", syllables: ["Is", "tas", "yon"], stress_index: 1, meaning: "Station", category: "Nouns" },
    { word: "Dálan", syllables: ["Dá", "lan"], stress_index: 0, meaning: "Street / Path", category: "Nouns" },
    { word: "Syudád", syllables: ["Syu", "dád"], stress_index: 1, meaning: "City", category: "Nouns" },
    { word: "Banwá", syllables: ["Ban", "wá"], stress_index: 1, meaning: "Town / Country", category: "Nouns" },
    { word: "Baryo", syllables: ["Bar", "yo"], stress_index: 0, meaning: "Village", category: "Nouns" },
    { word: "Pilipínas", syllables: ["Pi", "li", "pí", "nas"], stress_index: 2, meaning: "Philippines", category: "Nouns" },
    { word: "Amérika", syllables: ["A", "mé", "ri", "ka"], stress_index: 1, meaning: "America", category: "Nouns" },
    { word: "Ingglatéra", syllables: ["Ing", "gla", "té", "ra"], stress_index: 2, meaning: "England", category: "Nouns" },
    { word: "Hapón", syllables: ["Ha", "pón"], stress_index: 1, meaning: "Japan", category: "Nouns" },
    { word: "Tsína", syllables: ["Tsí", "na"], stress_index: 0, meaning: "China", category: "Nouns" },
    { word: "Koreá", syllables: ["Ko", "re", "á"], stress_index: 2, meaning: "Korea", category: "Nouns" },
    { word: "Spány", syllables: ["Spány"], stress_index: 0, meaning: "Spain", category: "Nouns" },
    { word: "Práns", syllables: ["Práns"], stress_index: 0, meaning: "France", category: "Nouns" },
    { word: "Itály", syllables: ["I", "tá", "ly"], stress_index: 1, meaning: "Italy", category: "Nouns" },
    { word: "Alemánya", syllables: ["A", "le", "má", "nya"], stress_index: 2, meaning: "Germany", category: "Nouns" },
    { word: "Rúsya", syllables: ["Rús", "ya"], stress_index: 0, meaning: "Russia", category: "Nouns" },
    { word: "Indiyá", syllables: ["In", "di", "yá"], stress_index: 2, meaning: "India", category: "Nouns" },
    { word: "Osturalyá", syllables: ["Os", "tu", "ra", "lyá"], stress_index: 3, meaning: "Australia", category: "Nouns" },
    { word: "Kanadá", syllables: ["Ka", "na", "dá"], stress_index: 2, meaning: "Canada", category: "Nouns" },
    { word: "Mehéko", syllables: ["Me", "hé", "ko"], stress_index: 1, meaning: "Mexico", category: "Nouns" },
    { word: "Brásil", syllables: ["Brá", "sil"], stress_index: 0, meaning: "Brazil", category: "Nouns" },
    { word: "Áprika", syllables: ["Á", "pri", "ka"], stress_index: 0, meaning: "Africa", category: "Nouns" },
    { word: "Iuróp", syllables: ["Iu", "róp"], stress_index: 1, meaning: "Europe", category: "Nouns" },
    { word: "Ásya", syllables: ["Ás", "ya"], stress_index: 0, meaning: "Asia", category: "Nouns" },
    { word: "Línggwáhé", syllables: ["Líng", "gwá", "hé"], stress_index: 1, meaning: "Language", category: "Nouns" },
    { word: "Ilónggo", syllables: ["I", "lóng", "go"], stress_index: 1, meaning: "Ilonggo / Hiligaynon", category: "Nouns" },
    { word: "Ingglis", syllables: ["Ing", "glis"], stress_index: 0, meaning: "English", category: "Nouns" },
    { word: "Tagálog", syllables: ["Ta", "gá", "log"], stress_index: 1, meaning: "Tagalog", category: "Nouns" },
    { word: "Spányis", syllables: ["Spán", "yis"], stress_index: 0, meaning: "Spanish", category: "Nouns" },
    { word: "Pránsés", syllables: ["Prán", "sés"], stress_index: 1, meaning: "French", category: "Nouns" },
    { word: "Tsína", syllables: ["Tsí", "na"], stress_index: 0, meaning: "Chinese", category: "Nouns" },
    { word: "Hapón", syllables: ["Ha", "pón"], stress_index: 1, meaning: "Japanese", category: "Nouns" },
    { word: "Dág-on", syllables: ["Dág", "on"], stress_index: 0, meaning: "Year", category: "Nouns" },
    { word: "Búlan", syllables: ["Bú", "an"], stress_index: 0, meaning: "Month / Moon", category: "Nouns" },
    { word: "Semána", syllables: ["Se", "má", "na"], stress_index: 1, meaning: "Week", category: "Nouns" },
    { word: "Ádlaw", syllables: ["Ád", "law"], stress_index: 0, meaning: "Day / Sun", category: "Nouns" },
    { word: "Óras", syllables: ["Ó", "ras"], stress_index: 0, meaning: "Hour / Time", category: "Nouns" },
    { word: "Minúto", syllables: ["Mi", "nú", "to"], stress_index: 1, meaning: "Minute", category: "Nouns" },
    { word: "Segúndo", syllables: ["Se", "gún", "do"], stress_index: 1, meaning: "Second", category: "Nouns" },
    { word: "Ága", syllables: ["Á", "ga"], stress_index: 0, meaning: "Morning", category: "Nouns" },
    { word: "Udtú", syllables: ["Ud", "tú"], stress_index: 1, meaning: "Noon / Midday", category: "Nouns" },
    { word: "Hápun", syllables: ["Há", "pun"], stress_index: 0, meaning: "Afternoon", category: "Nouns" },
    { word: "Gab-í", syllables: ["Gab", "í"], stress_index: 1, meaning: "Night / Evening", category: "Nouns" },
    { word: "Gún-ub", syllables: ["Gún", "ub"], stress_index: 0, meaning: "Dawn", category: "Nouns" },
    { word: "Karón", syllables: ["Ka", "rón"], stress_index: 1, meaning: "Later / Now", category: "Grammar & Particles" },
    { word: "Kádasón", syllables: ["Ká", "da", "són"], stress_index: 2, meaning: "Next time", category: "Grammar & Particles" },
    { word: "Ága", syllables: ["Á", "ga"], stress_index: 0, meaning: "Early", category: "Adjectives" },
    { word: "Úlihí", syllables: ["Ú", "li", "hí"], stress_index: 2, meaning: "Late", category: "Adjectives" },
    { word: "Dasíg", syllables: ["Da", "síg"], stress_index: 1, meaning: "Fast / Quick", category: "Adjectives" },
    { word: "Hináy", syllables: ["Hi", "náy"], stress_index: 1, meaning: "Slow", category: "Adjectives" },
    { word: "Bag-ó", syllables: ["Bag", "ó"], stress_index: 1, meaning: "New", category: "Adjectives" },
    { word: "Dáan", syllables: ["Dá", "an"], stress_index: 0, meaning: "Old (objects)", category: "Adjectives" },
    { word: "Tígulang", syllables: ["Tí", "gu", "lang"], stress_index: 0, meaning: "Old (people)", category: "Adjectives" },
    { word: "Bátà", syllables: ["Bá", "tà"], stress_index: 0, meaning: "Young / Child", category: "Adjectives" },
    { word: "Mahál", syllables: ["Ma", "hál"], stress_index: 1, meaning: "Expensive / Dear", category: "Adjectives" },
    { word: "Barátu", syllables: ["Ba", "rá", "tu"], stress_index: 1, meaning: "Cheap", category: "Adjectives" },
    { word: "Nanamì", syllables: ["Na", "na", "mì"], stress_index: 2, meaning: "Beautiful / Nice", category: "Adjectives" },
    { word: "Maláway", syllables: ["Ma", "lá", "way"], stress_index: 1, meaning: "Ugly / Dirty", category: "Adjectives" },
    { word: "Matínlo", syllables: ["Ma", "tín", "lo"], stress_index: 1, meaning: "Clean", category: "Adjectives" },
    { word: "Mahigkô", syllables: ["Ma", "hig", "kô"], stress_index: 2, meaning: "Dirty", category: "Adjectives" },
    { word: "Mapútì", syllables: ["Ma", "pú", "tì"], stress_index: 1, meaning: "White", category: "Adjectives" },
    { word: "Maítúm", syllables: ["Ma", "i", "túm"], stress_index: 2, meaning: "Black", category: "Adjectives" },
    { word: "Mapulá", syllables: ["Ma", "pu", "lá"], stress_index: 2, meaning: "Red", category: "Adjectives" },
    { word: "Asúl", syllables: ["A", "súl"], stress_index: 1, meaning: "Blue", category: "Adjectives" },
    { word: "Bérde", syllables: ["Bér", "de"], stress_index: 0, meaning: "Green", category: "Adjectives" },
    { word: "Amárilyo", syllables: ["A", "má", "ril", "yo"], stress_index: 1, meaning: "Yellow", category: "Adjectives" },
    { word: "Oríntz", syllables: ["O", "ríntz"], stress_index: 1, meaning: "Orange", category: "Adjectives" },
    { word: "Pórpol", syllables: ["Pór", "pol"], stress_index: 0, meaning: "Purple", category: "Adjectives" },
    { word: "Bráun", syllables: ["Bráun"], stress_index: 0, meaning: "Brown", category: "Adjectives" },
    { word: "Gústo", syllables: ["Gús", "to"], stress_index: 0, meaning: "Like / Want", category: "Verbs" },
    { word: "Hídi", syllables: ["Hí", "di"], stress_index: 0, meaning: "Don't like / Refuse", category: "Verbs" },
    { word: "Naburúng", syllables: ["Na", "bu", "rúng"], stress_index: 2, meaning: "Surprised / Confused", category: "Adjectives" },
    { word: "Nahádlok", syllables: ["Na", "há", "dlok"], stress_index: 1, meaning: "Afraid", category: "Adjectives" },
    { word: "Napáy-id", syllables: ["Na", "páy", "id"], stress_index: 1, meaning: "Exhausted", category: "Adjectives" },
    { word: "Nakalípay", syllables: ["Na", "ka", "lí", "pay"], stress_index: 2, meaning: "Happy", category: "Adjectives" },
    { word: "Nasubô", syllables: ["Na", "su", "bô"], stress_index: 2, meaning: "Sad", category: "Adjectives" },
    { word: "Nahangít", syllables: ["Na", "ha", "ngít"], stress_index: 2, meaning: "Angry", category: "Adjectives" },
    { word: "Púlus", syllables: ["Pú", "lus"], stress_index: 0, meaning: "Worthless / No use", category: "Adjectives" }
];

// Apply slice
for (let i = 0; i < batch_50_300.length; i++) {
    data[50 + i] = batch_50_300[i];
}

fs.writeFileSync(VOCAB_PATH, JSON.stringify(data, null, 4));

// Update progress
fs.writeFileSync(PROG_PATH, JSON.stringify({ last_index: 301 }));

console.log("SUCCESS: Indices 50 to 300 have been Master Audited and Saved.");
